### PR TITLE
Handle messages containing only end boundary, fixes #38

### LINKED ISSUE #38: MultipartParseError when parsing empty message
Parsing an empty message, i.e. a message with only the final boundary, raises MultipartParseError in `MultipartParser._internal_write`:
```
Traceback (most recent call last):
  File "/tmp/repro.py", line 5, in <module>
    parser.write(b"--" + boundary + b"--\r\n")
  File "/tmp/python-multipart/multipart/multipart.py", line 1076, in write
    l = self._internal_write(data, data_len)
  File "/tmp/python-multipart/multipart/multipart.py", line 1154, in _internal_write
    raise e
multipart.exceptions.MultipartParseError: Did not find CR at end of boundary (3)
```

How to reproduce (ed8c47a):
```python
import multipart

boundary = b"-"
parser = multipart.MultipartParser(boundary)
parser.write(b"--" + boundary + b"--\r\n")
```

Firefox and Chrome produce empty messages like this, e.g. when POSTing a HTML form with only a unchecked checkbox.

### PR DESCRIPTION
**Pull request by jhnstrk**
Some browsers create empty messages when forms are posted - see #38 for examples.

The fix here adds a new state in the parser which is entered when the first hyphen after the first boundary is encountered. This is only the case for the very first boundary. Anything but a second hyphen after the first is considered an error.

### CODE REVIEW

**Comment by jhnstrk** [comment]
To me the spec isn't 100% clear. [rfc2046](https://datatracker.ietf.org/doc/html/rfc2046#section-5.1) appears to assume that there is always at least one body part, so this would not be valid. But it doesn't make it clear how a form with no parts should be communicated either.

Anyway, it's what Chrome (and probably Firefox, but I haven't tested myself) does now. Take the following text, adapted from the examples in #38
- save as a test.html
- open the file in Chrome
- open Chrome dev tools
- click the button on the form
- inspect the payload sent to example.com (Network tab,--> Payload --> View Source) 

```
<!DOCTYPE html>
<html>
  <head><meta charset="UTF-8"></head>
  <body>
        <form action="http://example.com/" enctype="multipart/form-data" method="post">
            <input type="checkbox" id="check" name="check">
            <label for="check">Breaks unless you check it</label>
			<input type="submit" value="Submit">
        </form>  
  </body>
</html>
```

I got the following payload: (Chrome Version 124.0.6367.61 (Official Build) (64-bit))
```
------WebKitFormBoundaryBBDliyOmePSMlFiJ--
```

Clicking (enabling) the check box in the form gives valid content with 1 part.

**Comment by jhnstrk** [comment]
Rebased on current master.

**Review by Kludex — APPROVED** [review]

**Comment by Kludex** [comment]
@jhnstrk I think my previous PR to fix the security advisory put this PR in a non-perfect state:

If I run what you suggest:
```py
import python_multipart

boundary = b"-"
parser = python_multipart.MultipartParser(boundary)
parser.write(b"------WebKitFormBoundaryBBDliyOmePSMlFiJ--\r\n")
```

I get `Skipping data after last boundary`, because `-` is computed on the END step.

Do you have suggestions on how we should fix it?

**Comment by jhnstrk** [comment]
> @jhnstrk I think my previous PR to fix the security advisory put this PR in a non-perfect state:
> 
> If I run what you suggest:
> 
> 
> I get `Skipping data after last boundary`, because `-` is computed on the END step.
> 
> Do you have suggestions on how we should fix it?

This is expected though... setting the boundary to `"-"` makes the initial part of the message (`-----`) appear valid: you have an initial two hyphens, boundary, then trailing hyphens.. Everything after looks like a bad trailing boundary (by the spec only whitespace followed by CRLF is allowed). We could validate this more strictly, but it's a little out of scope here.

To test the empty message case you should use
```python
boundary = b"----WebKitFormBoundaryBBDliyOmePSMlFiJ"
```

**Review by Kludex — APPROVED** [review]

**Pull request merged**
