### PR TITLE
README.md: hyperlink to documentation

### PR DESCRIPTION
**Pull request by yecril23pl**

### CODE REVIEW

**Comment by yecril23pl** [comment]
> @yecril23pl Do you changing this to what we have in Starlette: https://github.com/encode/starlette (the "Documentation" between `---`?

No, I do not.  A URL is not something that a reader would like to see.

**Comment by Kludex** [comment]
Sorry, I had a typo on my message.

**Comment by Kludex** [comment]
Feel free to open a PR analogous to what we have in Starlette. I'll close this for now.

**Comment by Kludex** [comment]
I've merged this because I didn't know how to reach the documentation 👀

**Comment by yecril23pl** [comment]
Wow.  Just wow.  Please be aware that this is not some random Python package, it is *the official replacement* for bundled `cgi` that has been deprecated.  You are a Python VIP now, please act accordingly 😉

**Comment by Kludex** [comment]
> Wow.  Just wow.  Please be aware that this is not some random Python package, it is *the official replacement* for bundled `cgi` that has been deprecated.  You are a Python VIP now, please act accordingly 😉

Excuse me?

**Comment by yecril23pl** [comment]
I understood this exchange as you refusing to acknowledge my argument against your review.  While this is a common occurrence in private projects, projects that have gained crucial external importance such as this one cause earthquakes in the community if under authoritarian management (e.g. XFree86).

**Comment by Kludex** [comment]
Locking this to avoid further heat discussion that does not benefit anyone.

**Pull request merged**
